---
title: "ESM 262 Assignment 2a"
author: "Evan Heberlein, Nikole Vannest, Ruoyu Wang"
date: "2/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
library(tidyverse)
```

```{r function}
# copy and paste the function from .R
v_power <- function(v, m){
  c_rolling = 0.015
  c_drag = 0.3
  g = 9.8     # in m/s2
  p_air = 1.2 # in kg/m3
  A = 9       # in m2
  
  pb = c_rolling*m*g*v + 0.5*A*p_air*c_drag*v^3
  return(pb)
}
```

```{r plug-in-nums}
# assign two masses
m1 = 31752
m2 = m1 * 0.75

power_df <- data_frame(
  speed = c(30, 22.22, 33.33, 11.11),
  power_1 = v_power(v = c(30, 22.22, 33.33, 11.11), m = m1),
  power_2 = v_power(v = c(30, 22.22, 33.33, 11.11), m = m2)
)

m1
m2
power_df
```

```{r plot}
ggplot()+
  geom_line(data = power_df, 
            aes(x = speed, y = power_1),
            color = "blue", size = 1)+
  geom_line(data = power_df, 
            aes(x = speed, y = power_2),
            color = "green", size = 1)+
  annotate("text", x = c(35,35), y = c(220000, 180000),
           label = c("Heavy", "Light"),
           color = c("blue", "green"))+
  labs(x = "Speed (m/s)", y = "Automobile Power (Watts)",
       title = "Vehicle power versus speed plot")+
  theme_minimal()

ggsave("ETH_NV_RW-Assignment2a-plot.png", height = 4, width = 6)
```

